version: "3.1"

services:
    mysql:
        image: mysql:5.7.31
        container_name: "relayer_mysql"
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
        restart: always
        ports:
            - 9011:3306
        environment:
            MYSQL_ROOT_PASSWORD: relayersecret
            MYSQL_DATABASE: relayer
            MYSQL_USER: root
            MYSQL_PASSWORD: relayersecret
        volumes:
            - mysql:/var/lib/mysql

volumes:
    mysql:
